name: sync github repo to gitee mirror

# Trigger behavior
on: push

jobs:

  mirror-sync:

    runs-on: ubuntu-latest

    # Environment variable
    env:

      # Gitee Private Key
      # https://gitee.com/profile/sshkeys
      dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}

      # Gitee Token
      # https://gitee.com/profile/personal_access_tokens
      dst_token: ${{ secrets.GITEE_TOKEN }}

      # The Gitee User
      # If the current repository belongs to an organization, the value of
      # the gitee_user variable must be set to the name of the organization,
      # such as ituknown.
      # Otherwise, it needs to be set to the personal username of github
      gitee_user: ${{ secrets.GITEE_USER }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        #with:
          #persist-credentials: false

      - name: Mirror the Github organization repos to Gitee.
        uses: Yikun/hub-mirror-action@master
        with:

          #cache_path: /github/workspace/hub-mirror-cache

          src: 'github/zlbr'
          dst: 'gitee/zlbr'

          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}

          # org or user, default is user
          account_type: user
          force_update: true
          debug: true

          #white_list: 'normal,test,empty'
          #black_list: 'test'

          # current repostory name
          # static_list: ${{ github.event.repository.name }}

          # static_list: 'repo_name,repo_name2'
          # black_list: 'repo_name,repo_name2'
          # white_list: 'repo_name,repo_name2'
